CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE auth (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id UUID NOT NULL UNIQUE,
  jwt_key VARCHAR(255) DEFAULT uuid_generate_v4() NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)