# Use the official PostgreSQL image as the base image
FROM postgres:latest

# Set the environment variables for the PostgreSQL database
ENV POSTGRES_USER your_username
ENV POSTGRES_PASSWORD your_password
ENV POSTGRES_DB your_database_name

EXPOSE 5432