services:

  db:
    image: go-auth-url-shortener-db
    restart: always
    container_name: url-shortener-db
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    volumes:
      - ./db/db_data:/data/db
    env_file:
      - ./db/.env
    ports:
      - "${DB_PORT}:27017"