FROM postgres:14

ARG DB_USER
ARG DB_PASSWORD
ARG DB_NAMENAME

# Указываем рабочий каталог по умолчанию
WORKDIR /db

# Используем значение переменной в контейнере
ENV POSTGRES_USER=$DB_USER
ENV POSTGRES_PASSWORD=$DB_PASSWORD
ENV POSTGRES_DB=$DB_NAME

# Открываем порт 5432 для удаленных подключений внутри контейнера
EXPOSE 5432
